import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import therapist from "/public/media/therapist-02.png";
import userAvatar from "/public/media/user-02.png";
import { ThreeDots } from "react-loader-spinner";

import { useState, useEffect, useRef } from "react";
import useScreenSize from "~/hooks/screenSize";

interface State {
  prompt: string;
  userPrompts: string[];
  therapistAnswer: string[];
  isThearapistTyping: boolean;
  screenHeight: number;
}

export default function Home() {
  const divRef = useRef<HTMLDivElement>(null);

  const mutation = api.langchain.chat.useMutation({
    onSuccess: (data) => {
      if (data) {
        setState((prevState) => ({
          ...prevState,
          therapistAnswer: [...prevState.therapistAnswer, data],
          isThearapistTyping: false,
        }));
        scrollToBottom();
      }
    },
  });

  useEffect(() => {
    setState((prevState) => ({
      ...prevState,
      screenHeight: screenHeight,
    }));
  }, []);

  const [state, setState] = useState<State>({
    prompt: "",
    userPrompts: [],
    therapistAnswer: [],
    isThearapistTyping: false,
    screenHeight: 0,
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setState({
      ...state,
      prompt: e.target.value,
    });
  };

  const scrollToBottom = () => {
    if (divRef.current) {
      divRef.current.scrollTop = divRef.current.scrollHeight;
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      handlePrompt();
    }
  };

  const screenHeight = (useScreenSize()?.height as number) - 100;

  const handlePrompt = async () => {
    setState((prevState) => ({
      ...prevState,
      userPrompts: [...prevState.userPrompts, prevState.prompt],
      prompt: "",
      isThearapistTyping: true,
    }));
    await mutation.mutate({ prompt: state.prompt });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-emerald-900 bg-gradient-to-b">
        <div
          className="top-0 flex h-full w-full flex-col items-start justify-start gap-4 overflow-scroll bg-emerald-900 p-8 md:h-full"
          style={{ height: `${screenHeight}px` }}
          ref={divRef}
        >
          <div className="flex w-full flex-row items-start justify-start gap-6 md:items-center">
            <Image
              src={therapist}
              sizes="100vw"
              unoptimized
              style={{
                width: "96px",
                height: "96px",
              }}
              alt="therapist-01"
            />
            <p className="whitespace-pre-line break-words rounded-md bg-[#2e8b57] p-3 text-sm font-normal leading-relaxed text-white shadow-md md:text-base lg:text-lg">
              Hello, I am your AI therapist. How can I help you today?
            </p>
          </div>

          {state.userPrompts.map((prompt, index) => (
            <div
              key={index}
              className="flex w-full flex-col items-center justify-start gap-6"
            >
              {/* User message */}
              <div className="flex w-full flex-row items-center justify-end gap-6 md:items-center">
                <p className="whitespace-pre-line break-words rounded-md bg-[#264577] p-3 text-sm font-normal leading-relaxed text-white shadow-md md:text-base lg:text-lg">
                  {prompt}
                </p>
                <Image
                  src={userAvatar}
                  sizes="100vw"
                  unoptimized
                  style={{
                    width: "96px",
                    height: "96px",
                  }}
                  alt="user-avatar"
                />
              </div>

              {/* Therapist response */}
              {state.therapistAnswer[index] && (
                <div className="flex w-full flex-row items-start justify-start gap-6 md:items-start">
                  <Image
                    src={therapist}
                    sizes="100vw"
                    unoptimized
                    style={{
                      width: "96px",
                      height: "96px",
                    }}
                    alt="therapist-avatar"
                  />
                  <p className="whitespace-pre-line break-words rounded-md bg-[#2e8b57] p-3 text-sm font-normal leading-relaxed text-white shadow-md md:text-base lg:text-lg">
                    {state.therapistAnswer[index]}
                  </p>
                </div>
              )}
            </div>
          ))}

          {state.isThearapistTyping && (
            <div className="flex w-full flex-row items-start justify-start gap-6 md:items-center">
              <ThreeDots
                visible={true}
                height="80"
                width="80"
                color="#4fa94d"
                radius="9"
                ariaLabel="three-dots-loading"
              />
            </div>
          )}
        </div>

        <div className="absolute bottom-0 flex w-full flex-row items-center justify-start gap-4 bg-teal-950 p-7">
          <input
            type="text"
            className="w-full rounded-lg px-4 py-2 font-semibold text-[#15162c]"
            value={state.prompt}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
          />
          <button
            onClick={handlePrompt}
            className="w-48 rounded-lg bg-[#f9a826] px-4 py-2 font-semibold text-[#15162c]"
          >
            Send
          </button>
        </div>
      </main>
    </>
  );
}
